apiVersion: v1
kind: Service
metadata:
  name: my-rancher
spec:
  type: LoadBalancer
  externalIPs:
  - MASTER_IP_ADDRESS
  selector:
    app: rancher
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  - name: https
    protocol: TCP
    port: 8080
    targetPort: 444
