apiVersion: v1
kind: Service
metadata:
  name: opensearch-expose
spec:
  type: LoadBalancer
  externalIPs:
  - MASTER_IP_ADDRESS
  selector:
    app: opensearch
  ports:
  - name: http
    protocol: TCP
    port: 9200
    targetPort: 9200
