apiVersion: v1
kind: Service
metadata:
  name: opensearch-coordinator-expose
spec:
  type: LoadBalancer
  externalIPs:
  - MASTER_IP_ADDRESS
  selector:
    app: coordinator
  ports:
  - name: http
    protocol: TCP
    port: 9200
    targetPort: 9200
