apiVersion: v1
kind: Service
metadata:
  name: grafana-expose
spec:
  type: LoadBalancer
  externalIPs:
  - MASTER_IP_ADDRESS
  selector:
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/name: grafana
  ports:
  - name: http
    protocol: TCP
    port: 3000
    targetPort: 3000
